server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: 1
  ## 此处填写你自己的七牛云 secret key
  secretKey: 2
  ## 此处填写你自己的七牛云 bucket
  bucket: 3
  ## 此处填写你自己的七牛云 域名
  prefix: 4
spring:
  servlet:
    multipart:
      enabled: true
#      location: /Users/yangkai.shen/Documents/code/back-end/spring-boot-demo/spring-boot-demo-upload/tmp
      location: E:\\
      file-size-threshold: 5MB
      max-file-size: 20MB
