server:
  port: 8080
  servlet:
    context-path: /demo


spring.thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  #热部署文件，页面不产生缓存，及时更新, 在开发阶段设置为false
  cache: false
